server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
 # servlet: 好像没什么用,配置后请求路径正确却无法访问
 #   #修改默认映射路径
 #   path: **.do
  servlet:
    context-path: /

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
    static-path-pattern: /static/
     #表示所有的访问都经过静态资源路径
    #static-path-pattern: /**
 #resources:
 #  static-locations: classpath:/static/**
  #172.17.0.1
  datasource:
      url: jdbc:mysql://localhost:3306/decorate?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&useSSL=false
      username: root
      password: root
      #com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        filters: stat
        max-active: 20
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
 # resources:
 #   static-locations: classpath:/WEB-INF/static


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.decorate.model
  configuration:
    lazy-loading-enabled: true
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #log-prefix: decorate
#pagehelperab
pagehelper:
  helperDialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #设置dialect分页无效,应该设置helperDialect
  #dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  page-size-zero: true
  offset-as-page-num: true
  row-bounds-with-count: true
  #dialect-alias: com.github.pagehelper.dialect.helper.MySqlDialect
logging:
  level:
    com.decorate.mapper : debug
#logging:
 # level: debug
  #config: classpath:logback.xml